services:
  resource-service:
    container_name: springboot-resource-service
    image: springboot-resource-service
    build: ./resource-service/
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql_resource_service
      - rabbitmq
  postgresql_resource_service:
    container_name: postgresql_resource_service
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_USER=${RESOURCE_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${RESOURCE_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${RESOURCE_SERVICE_POSTGRES_DB}
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5673:5672"
  resource-processor:
    container_name: springboot-resource-processor
    image: springboot-resource-processor
    build: ./resource_processor
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq
  song-service:
    container_name: springboot-song-service
    image: springboot-song-service
    build: ./song-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql_song_service
  postgresql_song_service:
    container_name: postgresql_song_service
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${SONG_SERVICE_POSTGRES_USER}
      - POSTGRES_PASSWORD=${SONG_SERVICE_POSTGRES_PASSWORD}
      - POSTGRES_DB=${SONG_SERVICE_POSTGRES_DB}
