services:
  app:
    container_name: springboot-resource-service
    image: springboot-resource-service
    build: ./
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgresql_resource_service
      - rabbitmq
  postgresql_resource_service:
    container_name: postgresql_resource_service
    image: postgres
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=resource_service_db
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
