services:
  resource-processor:
    container_name: springboot-resource-processor
    image: springboot-resource-processor
    build: ./
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - rabbitmq-resource-processor
